import type { NextPage } from 'next'
import Head from 'next/head'
import dynamic from "next/dynamic";

const NoSSRComponent = dynamic(() => import("../components/schema"), {
  ssr: false,
});

function getRandomColor() {
    var letters = '0123456789ABCDEF';
    var color = '#';
    for (var i = 0; i < 6; i++) {
        color += letters[Math.floor(Math.random() * 16)];
    }
    return color;
}

const initNodes = () => {
    const items = [];
    for (let i = 4; i < 8; i++) {
        items.push({
            x: i * 150,
            y: i * 100,
            width: 100,
            height: 100,
            id: 'node-' + i,
            rotation: Math.random() * 180,
            isDragging: false,
            fill: getRandomColor(),
            name: 'Lorem Ipsum is simply dummy text of the printing. ' + i,
        });
    }
    return items;
}

const initLinks = () => {
    const items = [];

    const source = initNodes()[0];
    const target = initNodes()[1];

    const source1 = initNodes()[1];
    const target1 = initNodes()[2];

    const source2 = initNodes()[2];
    const target2 = initNodes()[3];

    items.push(
        {
            source: {
                id: source.id,
                x: source.x,
                y: source.y,
                place: 0
            },
            target: {
                id: target.id,
                x: target.x,
                y: target.y,
                place: 1
            },
            color:getRandomColor(),
        },
        {
            source: {
                id: source1.id,
                x: source1.x,
                y: source1.y,
                place: 2
            },
            target: {
                id: target1.id,
                x: target1.x,
                y: target1.y,
                place: 3
            },
            color:getRandomColor(),
        },
        {
            source: {
                id: source2.id,
                x: source2.x,
                y: source2.y,
                place: 0
            },
            target: {
                id: target2.id,
                x: target2.x,
                y: target2.y,
                place: 1
            },
            color:getRandomColor(),
        },
        );
    return items;
}

const Home: NextPage = () => {
    const nodes = initNodes();
    const links = initLinks();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NoSSRComponent nodes={nodes} links={links}/>
    </div>
  )
}

export default Home
